  eeacms2elastic:
    build: eeacms2elastic
    volumes:
      - csvData:/tmp/csvData #must match OUPUTDIR env
      - kibanaBackup:/tmp/configurationKibana #must match KIBANACONFIGURATIONBACKUP env

    environment:
      LOGSTASH_RW_USERNAME: "changeme"
      LOGSTASH_RW_PASSWORD: "changeme"
      OUTPUTDIR: "/tmp/csvData"
      KIBANACONFIGURATIONDIR: "/tmp/configurationKibana"
      RESETATSTARTUP: "NO"
      CRON_ENTRY: "*/15 * * * *"
      DOWNLOADURL: "changeme"
      INDEXNAME: "changeme"
      DELIMITER: ";"
    links:
      - elasticsearch:elasticsearch
